### ISSUE TITLE
Error when trying to install via pip

### ISSUE THREAD

**Issue by smheidrich** [mir-group/flare#134]
This happens both on my local machine as well as on our cluster if I try to install the package via pip:

```bash
$ pip install mir-flare
Collecting mir-flare
  Using cached https://files.pythonhosted.org/packages/7d/5e/9692de4a76b732072d552cc229672d41a33153dcd3f3a850dedda3475b47/mir-flare-0.0.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c0v787oc/mir-flare/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c0v787oc/mir-flare/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-c0v787oc/mir-flare/pip-egg-info
         cwd: /tmp/pip-install-c0v787oc/mir-flare/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c0v787oc/mir-flare/setup.py", line 7, in <module>
        with open("requirements.txt", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

What seems to happen is that ``requirements.txt`` wasn't included in the sdist published on PyPI. If I build the sdist myself, it doesn't get included there, either.

There is a very easy way to fix this, though, PR incoming...

**Comment by smheidrich** [comment]
Fixed by 4685126c839c35a36811507cbaadfcedec59a3d3
