### ISSUE TITLE
Parallel TrajectoryTrainer with parallel GaussianProcess crashes

### ISSUE THREAD

**Issue by anjohan** [mir-group/flare#159]
I am essentially running the TrajectoryTrainer tutorial (kudos to @stevetorr for writing a scientific software tutorial that actually works!), but I added parallelization:
```python
from flare.gp_from_aimd import TrajectoryTrainer
from flare.gp import GaussianProcess
from flare.kernels.mc_simple import two_plus_three_body_mc, two_plus_three_body_mc_grad
from flare.struc import Structure
import ase.io.lammpsrun

with open("lammps.dump", "r") as f:
    traj = ase.io.lammpsrun.read_lammps_dump_text(f, index=slice(None))

struc_traj = []
for step in traj[-2:]:
    struc_traj.append(Structure.from_ase_atoms(step))
    struc_traj[-1].forces = step.get_forces()

traj = struc_traj
print(traj[0].forces)

gp = GaussianProcess(
    kernel=two_plus_three_body_mc,
    kernel_grad=two_plus_three_body_mc_grad,
    hyps=[0.01, 0.01, 0.01, 0.01, 0.01],
    cutoffs=(7, 7),
    hyp_labels=[
        "Two-Body Signal Variance",
        "Two-Body Length Scale",
        "Three-Body Signal Variance",
        "Three-Body Length Scale",
        "Noise Variance",
    ],
    par=True,
    n_cpus=6,
)

TT = TrajectoryTrainer(
    frames=traj,
    gp=gp,
    rel_std_tolerance=3,
    abs_std_tolerance=0,
    pre_train_on_skips=5,
    n_cpus=6,
    parallel=True,
    verbose=8,
)

TT.run()
```

I get the following error, indicating that one should not use a parallel TrajectoryTrainer with a parallel GaussianProcess.
```python
Commencing run with pre-run...
Now beginning pre-run activity.
Added 8 atoms to pretrain
Now commencing pre-run training of GP (which has non-empty training set)
=====NOW ON FRAME 0=====
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/anders/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/anders/miniconda3/lib/python3.7/site-packages/flare/predict.py", line 37, in predict_on_atom
    force, var = gp.predict(chemenv, i + 1)
  File "/home/anders/miniconda3/lib/python3.7/site-packages/flare/gp.py", line 334, in predict
    nsample=self.nsample)
  File "/home/anders/miniconda3/lib/python3.7/site-packages/flare/gp_algebra.py", line 885, in get_kernel_vector_par
    with mp.Pool(processes=n_cpus) as pool:
  File "/home/anders/miniconda3/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/anders/miniconda3/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/home/anders/miniconda3/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/home/anders/miniconda3/lib/python3.7/multiprocessing/process.py", line 110, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 45, in <module>
    TT.run()
  File "/home/anders/miniconda3/lib/python3.7/site-packages/flare/gp_from_aimd.py", line 304, in run
    self.pred_func(cur_frame, self.gp, self.n_cpus)
  File "/home/anders/miniconda3/lib/python3.7/site-packages/flare/predict.py", line 138, in predict_on_structure_par
    r = results[i].get()
  File "/home/anders/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError: daemonic processes are not allowed to have children
```
However, `gp_from_aimd.py` has the check
```python
if (parallel and gp.par and gp.per_atom_par):
```
which indicates that the double parallelization should be used.

I'm running version 0.0.10 (from pip).

Eh... @stevetorr ? @nw13slx ?

**Comment by nw13slx** [comment]
let me double check that one. It was an old problem for the per_atom_par and it's solved in the development branch.

**Comment by nw13slx** [comment]
For the master branch version, please follow the guidance of the tutorial in https://flare.readthedocs.io/en/latest/install.html#acceleration-with-multiprocessing-and-mkl and turn off the parallel set up in GPFA and OTF for parallelization. 

I'll update Steven's tutorial to add that sentence.
