### ISSUE TITLE
Problem with the on-the-fly learning with separate hyperparameters.

### ISSUE THREAD

**Issue by hhlim12** [mir-group/flare#308]
**Describe the bug**
Dear FLARE developer, I failed to run the on-the-fly learning with separate hyperparameters. I confirm that the OTF learning without separate hyperparameters run successfully. I wonder whether this feature has been implemented or not. Looking at the source code, I noticed that the stress related kernels: `efs_energy_kernel`, `efs_force_kernel`, `efs_self_kernel` have not been implemented for multielement kernel (mc_sephyps.py) and thus maybe result in the error that I got (see also the error message below). I have followed the manual on how to use this feature but I'm sorry If I missed some explanations.

Best regards,

Harry

https://github.com/mir-group/flare/blob/4de1cc2a639ee36bdcd265cf42bb0caa647a9db9/flare/gp.py#L143
https://github.com/mir-group/flare/blob/337d6c7db6fc9bd2caee67a158ff6274502e111d/flare/kernels/mc_sephyps.py#L3161
https://github.com/mir-group/flare/blob/337d6c7db6fc9bd2caee67a158ff6274502e111d/flare/kernels/mc_sephyps.py#L3162
https://github.com/mir-group/flare/blob/337d6c7db6fc9bd2caee67a158ff6274502e111d/flare/kernels/mc_sephyps.py#L3163

**To Reproduce**
Below is an example of script to reproduce the error.
```
import os, sys
from ase.build import molecule,fcc111, add_adsorbate
from flare.gp import GaussianProcess
from flare.ase.calculator import FLARE_Calculator
from ase import units
from ase.md.velocitydistribution import (MaxwellBoltzmannDistribution)
from flare.ase.otf import ASE_OTF
from flare.utils.parameter_helper import ParameterHelper
from ase.calculators.espresso import Espresso

n_cpus = int(sys.argv[1])
os.mkdir('BACKUP')

atoms_obj = fcc111('Pt', (2,2,4), vacuum = 10.0)
molecule_obj = molecule('CO')
add_adsorbate(atoms_obj, molecule_obj, height = 3.0, position='ontop')

pm = ParameterHelper(species=['Pt', 'C', 'O'],
                     kernels={'twobody':[['*', '*'], ['Pt','*'], ['Pt', 'Pt']],
                              'threebody':[['*', '*', '*'],
                                           ['Pt', '*', '*'],
                                           ['Pt', 'Pt', '*'],
                                           ['Pt', 'Pt', 'Pt']]},
                     parameters={'twobody0':[0.54, 1.17, 4.5], 'twobody1':[0.54, 1.17, 4.5], 'twobody2':[0.54, 1.17, 4.5],
                                 'threebody0':[0.001, 0.917], 'threebody1':[0.004, 0.917],
                                 'threebody2':[0.004, 0.917], 'threebody3':[0.004, 0.917],
                                 'cutoff_twobody':4.5,
                                 'cutoff_threebody':4.5,
                                 'noise': 0.015})

hyps_mask = pm.as_dict()
hyps = hyps_mask['hyps']
cutoffs = hyps_mask['cutoffs']
hyp_labels = hyps_mask['hyp_labels']
kernels = hyps_mask['kernels']

gp_model = GaussianProcess(
    kernels = kernels,
    component = 'mc',
    hyps_mask = hyps_mask,
    hyps = hyps,
    cutoffs = cutoffs,
    hyp_labels = hyp_labels,
    opt_algorithm = 'L-BFGS-B',
    parallel = True,
    per_atom_par = True,
    maxiter = 2,
    n_sample = 1,
    n_cpus = n_cpus
)

label = 'PtCO'
input_file = label+'.pwi'
output_file = label+'.pwo'
pw_loc = './pw.x'

os.environ['ASE_ESPRESSO_COMMAND'] = f'mpirun -np {n_cpus} {pw_loc} < {input_file} > {output_file}'

input_data = {
    "control": {"calculation": "scf",
                "pseudo_dir": "./"},
    "system": {
        "ecutwfc": 40.0,
        "ecutrho": 320.0,
        "smearing": "mp",
        "occupations": "smearing",
        "degauss": 0.01,
        "nbnd": 360,
    },
    "electrons": {"diagonalization": "david", "conv_thr": 1.0e-08, "mixing_beta": 0.1},
}
pseudopotentials = {
    'Pt': 'Pt.pbe-n-kjpaw_psl.1.0.0.UPF',
    'C': 'C.pbe-n-kjpaw_psl.1.0.0.UPF',
    'O': 'O.pbe-n-kjpaw_psl.1.0.0.UPF'
}

dft_calc = Espresso(pseudopotentials=pseudopotentials, label=label,
                    input_data = input_data,
                    tstress=True, tprnfor=True, nosym=True,
                    kpts=(4, 4, 1))


flare_calculator = FLARE_Calculator(gp_model,
                                    par = True,
                                    mgp_model = None,
                                    use_mapping = False)
atoms_obj.set_calculator(flare_calculator)


MaxwellBoltzmannDistribution(atoms_obj, temperature_K = 500, force_temp = True)
md_engine = 'VelocityVerlet'
md_kwargs = {}

otf_params = {'output_name': 'otf',
              'std_tolerance_factor': 1.5,
              'max_atoms_added' : 1,
              'write_model': 3}

test_otf = ASE_OTF(atoms_obj,
                   init_atoms = [0],
                   timestep = 1 * units.fs,
                   freeze_hyps = 1000,
                   force_only = True,
                   number_of_steps = 1,
                   dft_calc = dft_calc,
                   md_engine = md_engine,
                   md_kwargs = md_kwargs,
                   store_dft_output = ([f"{input_file}",f"{output_file}"], './BACKUP'),
                   **otf_params)

test_otf.run()
print ("FINISH")
```

**Expected behavior**
The OTF learning is performed successfully.

**Screenshots**
Error message:
```
"""
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/predict.py", line 92, in predict_on_atom_efs
    return gp.predict_efs(chemenv)
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/gp.py", line 763, in predict_efs
    energy_vector, force_array, stress_array = efs_kern_vec(
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/gp_algebra.py", line 1593, in efs_kern_vec
    force_arrays = efs_force_vector(
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/gp_algebra.py", line 1432, in efs_force_vector
    return efs_force_vector_unit(
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/gp_algebra.py", line 1211, in efs_force_vector_unit
    ef, ff, sf = efs_force_kernel(x, x_2, *args)
TypeError: 'str' object is not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "create_gp.py", line 112, in <module>
    test_otf.run()
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/otf.py", line 329, in run
    self.md_step()  # update positions by Verlet
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/ase/otf.py", line 220, in md_step
    self.md.step()
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/ase/md/verlet.py", line 56, in step
    forces = atoms.get_forces(md=True)
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/ase/atoms.py", line 788, in get_forces
    forces = self._calc.get_forces(self)
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/ase/calculators/abc.py", line 23, in get_forces
    return self.get_property('forces', atoms)
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/ase/calculators/calculator.py", line 737, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/ase/calculator.py", line 95, in calculate
    self.calculate_gp(atoms)
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/ase/calculator.py", line 106, in calculate_gp
    res = predict_on_structure_efs_par(
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/site-packages/flare/predict.py", line 339, in predict_on_structure_efs_par
    r = results[i].get()
  File "/home/user/miniconda3/envs/myflare/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'str' object is not callable
```

**Additional context**
I install FLARE by cloning the repo.

**Comment by hhlim12** [comment]
Hi, I would like to give update on this issue. I didn't find any error after modifying the following lines in the `calculator.py`:

**Original**
https://github.com/mir-group/flare/blob/5f14e22689768492f9fdd0203eaf6eb65bc843d4/flare/ase/calculator.py#L103-L120

**Modification**
```
    def calculate_gp(self, atoms):
        # Compute energy, forces, and stresses and their uncertainties
        nat = len(atoms)
        if self.par:
            res = predict_on_structure_par(
                atoms, self.gp_model, write_to_structure=False
            )
        else:
            res = predict_on_structure(
                atoms, self.gp_model, write_to_structure=False
            )

        # Set the energy, force, and stress attributes of the calculator.
        self.results["local_energies"] = np.zeros(nat)
        self.results["forces"] = res[0]
        self.results["partial_stresses"] = np.zeros((nat,6))
        self.results["local_energy_stds"] = np.zeros(nat)
        self.results["stds"] = res[1]
        self.results["partial_stress_stds"] = np.zeros((nat, 6))
```

I change the prediction function from `predict_on_structure_efs` to `predict_on_structure` which doesn't involve the `efs kernel`. I also specify the local energy and stress to be zero since the subsequent process might need those quantities to be exist.

Before modifying the `calculator.py`, I have tried to explicitly specified `calculate_efs = False` in the `ASE_OTF` parameter but it doesn't solve the problem (the stress is still calculated). It seems that option of `calculate_energy` and `calculate_efs` of the OTF class are not considered in the `calculate_gp` thus the FLARE calculator is forced to always calculate stress.

https://github.com/mir-group/flare/blob/5f14e22689768492f9fdd0203eaf6eb65bc843d4/flare/otf.py#L113-L114

Though no error is found, I'm not sure whether this modification is the correct way to solve the issue.

Best regards,

**Comment by YuuuXie** [comment]
Hi @hhlim12 , I think your modification will not have problem (if you don't need the energy and stress). And it might also make the on-the-fly training faster, since it is force only.

Thanks for reporting this. I'll close this issue for now, and you can reopen it if you still have problems
